apiVersion: v1
kind: Service
metadata:
  name: twitter-backend
  labels:
    app: twitter-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: twitter-backend