apiVersion: v1
kind: Service
metadata:
  labels:
    app: twitter-proxy
  name: twitter-proxy
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: twitter-proxy