name: 'CI'
description: 'A CI pipeline that builds and pushes docker images'

on:
  push:
    paths:
      - 'backend/src/**'
      - '@types/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        working-directory: ./backend
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build_backend
        working-directory: ./backend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: twitter-backend:latest
      - working-directory: ./backend
        name: Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}
