name: 'CI'

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'SFW_service/**'
      - 'nginx-server/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: backend-changed-files
        uses: tj-actions/changed-files@v8.9
        with:
          files: 'backend/**'
      - name: Set up Docker Buildx
        if: steps.backend-changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: steps.backend-changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        if: steps.backend-changed-files.outputs.any_changed == 'true'
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/twitter-backend:latest
          context: ./backend/
          file: ./backend/Dockerfile
      - name: Image digest
        if: steps.backend-changed-files.outputs.any_changed == 'true'
        run: echo ${{ steps.docker_build_backend.outputs.digest }}
  sfw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: sfw-changed-files
        uses: tj-actions/changed-files@v8.9
        with:
          files: 'SFW_service/**'
      - name: Set up Docker Buildx
        if: steps.sfw-changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: steps.sfw-changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        if: steps.sfw-changed-files.outputs.any_changed == 'true'
        id: docker_build_sfw
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/twitter-sfw:latest
          context: ./SFW_service/
          file: ./SFW_service/Dockerfile
      - name: Image digest
        if: steps.sfw-changed-files.outputs.any_changed == 'true'
        run: echo ${{ steps.docker_build_sfw.outputs.digest }}
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: proxy-changed-files
        uses: tj-actions/changed-files@v8.9
        with:
          files: 'nginx-server/**'
      - name: Set up Docker Buildx
        if: steps.proxy-changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: steps.proxy-changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        if: steps.proxy-changed-files.outputs.any_changed == 'true'
        id: docker_build_proxy
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/twitter-proxy:latest
          context: ./nginx-server/
          file: ./nginx-server/Dockerfile
      - name: Image digest
        if: steps.proxy-changed-files.outputs.any_changed == 'true'
        run: echo ${{ steps.docker_build_proxy.outputs.digest }}