name: test-and-build-the-backend
on: 
  pull_request:
    paths:
      - 'backend/src/**'
      - '@types/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - working-directory: ./backend
        run: npm install 
      - working-directory: ./backend
        run: npm run test
        env:
          DATABASE_URI:  ${{ secrets.DATABASE_URI }}
          PORT: '8000'
          TEST_DATABASE_URI: ${{ secrets.TEST_DATABASE_URI }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          UPLOADS_S3_BUCKET: ${{ secrets.UPLOADS_S3_BUCKET }}
          SIGNED_URL_EXPIRATION: '300'
          S3_USER: ${{ secrets.S3_USER }}
          S3_REGION: ${{ secrets.S3_REGION }}
          RABBIT_MQ_URI: ${{ secrets.RABBIT_MQ_URI }}
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - working-directory: ./backend
        run: npm install 
      - working-directory: ./backend
        run: npm run build 