name: test-and-build-the-backend
on: 
  pull_request:
    paths:
      - 'backend/src/**'
      - '@types/**'
      - 'package.json'
      - 'package-lock.json'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install 
      - run: npm run test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install 
      - run: npm run build 